name: Deploy Discord Bot to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2 and Restart Bot
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@54.208.130.81 << 'EOF'
          cd /home/ec2-user/team-1
          git pull origin main
          pkill -f discordbot.py || true
          nohup python3 discordbot.py > output.log 2>&1 &
        EOF
